// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_user.sql

package db

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, username, hashed_password, created_at FROM admin_users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdminUser(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, hashed_password, created_at FROM admin_users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, hashed_password, created_at FROM admin_users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAdminUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]AdminUser, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUserPassword = `-- name: UpdateAdminUserPassword :exec
UPDATE admin_users
SET hashed_password = $2
WHERE id = $1
`

type UpdateAdminUserPasswordParams struct {
	ID             int64  `json:"id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserPassword, arg.ID, arg.HashedPassword)
	return err
}
