// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_user_role.sql

package db

import (
	"context"
)

const createAdminUserRole = `-- name: CreateAdminUserRole :exec
INSERT INTO admin_user_roles (
    admin_user_id,
    role_id
) VALUES (
    $1, $2
)
`

type CreateAdminUserRoleParams struct {
	AdminUserID int64 `json:"admin_user_id"`
	RoleID      int64 `json:"role_id"`
}

func (q *Queries) CreateAdminUserRole(ctx context.Context, arg CreateAdminUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, createAdminUserRole, arg.AdminUserID, arg.RoleID)
	return err
}

const deleteAdminUserRoles = `-- name: DeleteAdminUserRoles :exec
DELETE FROM admin_user_roles
WHERE admin_user_id = $1
`

func (q *Queries) DeleteAdminUserRoles(ctx context.Context, adminUserID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminUserRoles, adminUserID)
	return err
}

const listAdminUserRoles = `-- name: ListAdminUserRoles :many
SELECT aur.admin_user_id, r.id AS role_id, r.name
FROM admin_user_roles aur
JOIN roles r ON r.id = aur.role_id
ORDER BY aur.admin_user_id, r.id
`

type ListAdminUserRolesRow struct {
	AdminUserID int64  `json:"admin_user_id"`
	RoleID      int64  `json:"role_id"`
	Name        string `json:"name"`
}

func (q *Queries) ListAdminUserRoles(ctx context.Context) ([]ListAdminUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUserRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUserRolesRow{}
	for rows.Next() {
		var i ListAdminUserRolesRow
		if err := rows.Scan(&i.AdminUserID, &i.RoleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
