// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_user.sql

package db

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*) FROM admin_users
WHERE ($1::bool OR deleted_at IS NULL)
`

func (q *Queries) CountAdminUsers(ctx context.Context, includeDeleted bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers, includeDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    username,
    hashed_password
) VALUES (
    $1, $2
) RETURNING id, username, hashed_password, created_at, deleted_at
`

type CreateAdminUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser, arg.Username, arg.HashedPassword)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, username, hashed_password, created_at, deleted_at FROM admin_users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAdminUser(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, hashed_password, created_at, deleted_at FROM admin_users
WHERE username = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, hashed_password, created_at, deleted_at FROM admin_users
WHERE ($1::bool OR deleted_at IS NULL)
ORDER BY id
LIMIT $3
OFFSET $2
`

type ListAdminUsersParams struct {
	IncludeDeleted bool  `json:"include_deleted"`
	PageOffset     int32 `json:"page_offset"`
	PageLimit      int32 `json:"page_limit"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]AdminUser, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers, arg.IncludeDeleted, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAdminUser = `-- name: RestoreAdminUser :execrows
UPDATE admin_users
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreAdminUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreAdminUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteAdminUser = `-- name: SoftDeleteAdminUser :execrows
UPDATE admin_users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAdminUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteAdminUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAdminUserPassword = `-- name: UpdateAdminUserPassword :exec
UPDATE admin_users
SET hashed_password = $2
WHERE id = $1
`

type UpdateAdminUserPasswordParams struct {
	ID             int64  `json:"id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserPassword, arg.ID, arg.HashedPassword)
	return err
}
