// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_log.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countOperationLogs = `-- name: CountOperationLogs :one
SELECT count(*) FROM operation_logs
`

func (q *Queries) CountOperationLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperationLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOperationLogsSince = `-- name: CountOperationLogsSince :one
SELECT count(*) FROM operation_logs
WHERE created_at >= $1
`

// Dashboard 統計：某時間點之後的操作數（今日 = 本地時區當天 0 點起）
func (q *Queries) CountOperationLogsSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperationLogsSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOperationLog = `-- name: CreateOperationLog :one
INSERT INTO operation_logs (
    user_id, username, method, path, request_body, status_code, request_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, username, method, path, request_body, status_code, request_id, created_at
`

type CreateOperationLogParams struct {
	UserID      sql.NullInt64 `json:"user_id"`
	Username    string        `json:"username"`
	Method      string        `json:"method"`
	Path        string        `json:"path"`
	RequestBody string        `json:"request_body"`
	StatusCode  int32         `json:"status_code"`
	RequestID   string        `json:"request_id"`
}

func (q *Queries) CreateOperationLog(ctx context.Context, arg CreateOperationLogParams) (OperationLog, error) {
	row := q.db.QueryRowContext(ctx, createOperationLog,
		arg.UserID,
		arg.Username,
		arg.Method,
		arg.Path,
		arg.RequestBody,
		arg.StatusCode,
		arg.RequestID,
	)
	var i OperationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Method,
		&i.Path,
		&i.RequestBody,
		&i.StatusCode,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOperationLogsBefore = `-- name: DeleteOperationLogsBefore :execrows
DELETE FROM operation_logs
WHERE created_at < $1
`

func (q *Queries) DeleteOperationLogsBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOperationLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listOperationLogs = `-- name: ListOperationLogs :many
SELECT id, user_id, username, method, path, request_body, status_code, request_id, created_at FROM operation_logs
ORDER BY id DESC
LIMIT $1
OFFSET $2
`

type ListOperationLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOperationLogs(ctx context.Context, arg ListOperationLogsParams) ([]OperationLog, error) {
	rows, err := q.db.QueryContext(ctx, listOperationLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationLog{}
	for rows.Next() {
		var i OperationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Method,
			&i.Path,
			&i.RequestBody,
			&i.StatusCode,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
