// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db

import (
	"context"
)

const listPermissionCodesByAdminUserID = `-- name: ListPermissionCodesByAdminUserID :many
SELECT DISTINCT p.code
FROM admin_user_roles aur
JOIN role_permissions rp ON rp.role_id = aur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE aur.admin_user_id = $1
ORDER BY p.code
`

func (q *Queries) ListPermissionCodesByAdminUserID(ctx context.Context, adminUserID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionCodesByAdminUserID, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
