// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	CountOperationLogs(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateOperationLog(ctx context.Context, arg CreateOperationLogParams) (OperationLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, userID int64) (Wallet, error)
	DeleteOperationLogsBefore(ctx context.Context, createdAt time.Time) (int64, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWalletByUserID(ctx context.Context, userID int64) (Wallet, error)
	ListOperationLogs(ctx context.Context, arg ListOperationLogsParams) ([]OperationLog, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
