// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_permission.sql

package db

import (
	"context"
)

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT rp.role_id, p.code, p.description
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
ORDER BY rp.role_id, p.code
`

type ListRolePermissionsRow struct {
	RoleID      int64  `json:"role_id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

func (q *Queries) ListRolePermissions(ctx context.Context) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.RoleID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
