// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_entry.sql

package db

import (
	"context"
)

const countWalletEntries = `-- name: CountWalletEntries :one
SELECT count(*) FROM wallet_entries
WHERE wallet_id = $1
`

func (q *Queries) CountWalletEntries(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWalletEntries, walletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWalletEntry = `-- name: CreateWalletEntry :one
INSERT INTO wallet_entries (
    wallet_id, amount, note, operator_id, operator_username
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, wallet_id, amount, note, operator_id, operator_username, created_at
`

type CreateWalletEntryParams struct {
	WalletID         int64  `json:"wallet_id"`
	Amount           int64  `json:"amount"`
	Note             string `json:"note"`
	OperatorID       int64  `json:"operator_id"`
	OperatorUsername string `json:"operator_username"`
}

func (q *Queries) CreateWalletEntry(ctx context.Context, arg CreateWalletEntryParams) (WalletEntry, error) {
	row := q.db.QueryRowContext(ctx, createWalletEntry,
		arg.WalletID,
		arg.Amount,
		arg.Note,
		arg.OperatorID,
		arg.OperatorUsername,
	)
	var i WalletEntry
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Note,
		&i.OperatorID,
		&i.OperatorUsername,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletEntries = `-- name: ListWalletEntries :many
SELECT id, wallet_id, amount, note, operator_id, operator_username, created_at FROM wallet_entries
WHERE wallet_id = $1
ORDER BY id DESC
LIMIT $2
OFFSET $3
`

type ListWalletEntriesParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListWalletEntries(ctx context.Context, arg ListWalletEntriesParams) ([]WalletEntry, error) {
	rows, err := q.db.QueryContext(ctx, listWalletEntries, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletEntry{}
	for rows.Next() {
		var i WalletEntry
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Amount,
			&i.Note,
			&i.OperatorID,
			&i.OperatorUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
