// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    user_id
) VALUES (
    $1
) RETURNING id, user_id, balance, created_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, balance, created_at FROM wallets
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
