// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kys20548/template_golang_web/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go github.com/kys20548/template_golang_web/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/kys20548/template_golang_web/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountAdminUsers mocks base method.
func (m *MockStore) CountAdminUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAdminUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAdminUsers indicates an expected call of CountAdminUsers.
func (mr *MockStoreMockRecorder) CountAdminUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAdminUsers", reflect.TypeOf((*MockStore)(nil).CountAdminUsers), ctx)
}

// CountOperationLogs mocks base method.
func (m *MockStore) CountOperationLogs(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOperationLogs", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOperationLogs indicates an expected call of CountOperationLogs.
func (mr *MockStoreMockRecorder) CountOperationLogs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOperationLogs", reflect.TypeOf((*MockStore)(nil).CountOperationLogs), ctx)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), ctx)
}

// CountWallets mocks base method.
func (m *MockStore) CountWallets(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWallets", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWallets indicates an expected call of CountWallets.
func (mr *MockStoreMockRecorder) CountWallets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWallets", reflect.TypeOf((*MockStore)(nil).CountWallets), ctx)
}

// CreateAdminUser mocks base method.
func (m *MockStore) CreateAdminUser(ctx context.Context, arg db.CreateAdminUserParams) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", ctx, arg)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockStoreMockRecorder) CreateAdminUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockStore)(nil).CreateAdminUser), ctx, arg)
}

// CreateAdminUserRole mocks base method.
func (m *MockStore) CreateAdminUserRole(ctx context.Context, arg db.CreateAdminUserRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdminUserRole indicates an expected call of CreateAdminUserRole.
func (mr *MockStoreMockRecorder) CreateAdminUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserRole", reflect.TypeOf((*MockStore)(nil).CreateAdminUserRole), ctx, arg)
}

// CreateAdminUserTx mocks base method.
func (m *MockStore) CreateAdminUserTx(ctx context.Context, arg db.CreateAdminUserTxParams) (db.CreateAdminUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserTx", ctx, arg)
	ret0, _ := ret[0].(db.CreateAdminUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUserTx indicates an expected call of CreateAdminUserTx.
func (mr *MockStoreMockRecorder) CreateAdminUserTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserTx", reflect.TypeOf((*MockStore)(nil).CreateAdminUserTx), ctx, arg)
}

// CreateOperationLog mocks base method.
func (m *MockStore) CreateOperationLog(ctx context.Context, arg db.CreateOperationLogParams) (db.OperationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperationLog", ctx, arg)
	ret0, _ := ret[0].(db.OperationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperationLog indicates an expected call of CreateOperationLog.
func (mr *MockStoreMockRecorder) CreateOperationLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperationLog", reflect.TypeOf((*MockStore)(nil).CreateOperationLog), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(ctx context.Context, arg db.CreateUserTxParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), ctx, arg)
}

// CreateWallet mocks base method.
func (m *MockStore) CreateWallet(ctx context.Context, userID int64) (db.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, userID)
	ret0, _ := ret[0].(db.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockStoreMockRecorder) CreateWallet(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockStore)(nil).CreateWallet), ctx, userID)
}

// DeleteAdminUserRoles mocks base method.
func (m *MockStore) DeleteAdminUserRoles(ctx context.Context, adminUserID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdminUserRoles", ctx, adminUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdminUserRoles indicates an expected call of DeleteAdminUserRoles.
func (mr *MockStoreMockRecorder) DeleteAdminUserRoles(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdminUserRoles", reflect.TypeOf((*MockStore)(nil).DeleteAdminUserRoles), ctx, adminUserID)
}

// DeleteOperationLogsBefore mocks base method.
func (m *MockStore) DeleteOperationLogsBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperationLogsBefore", ctx, createdAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperationLogsBefore indicates an expected call of DeleteOperationLogsBefore.
func (mr *MockStoreMockRecorder) DeleteOperationLogsBefore(ctx, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperationLogsBefore", reflect.TypeOf((*MockStore)(nil).DeleteOperationLogsBefore), ctx, createdAt)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// GetAdminUser mocks base method.
func (m *MockStore) GetAdminUser(ctx context.Context, id int64) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", ctx, id)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockStoreMockRecorder) GetAdminUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockStore)(nil).GetAdminUser), ctx, id)
}

// GetAdminUserByUsername mocks base method.
func (m *MockStore) GetAdminUserByUsername(ctx context.Context, username string) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserByUsername", ctx, username)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserByUsername indicates an expected call of GetAdminUserByUsername.
func (mr *MockStoreMockRecorder) GetAdminUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserByUsername", reflect.TypeOf((*MockStore)(nil).GetAdminUserByUsername), ctx, username)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, id int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// ListAdminUserRoles mocks base method.
func (m *MockStore) ListAdminUserRoles(ctx context.Context) ([]db.ListAdminUserRolesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUserRoles", ctx)
	ret0, _ := ret[0].([]db.ListAdminUserRolesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUserRoles indicates an expected call of ListAdminUserRoles.
func (mr *MockStoreMockRecorder) ListAdminUserRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUserRoles", reflect.TypeOf((*MockStore)(nil).ListAdminUserRoles), ctx)
}

// ListAdminUsers mocks base method.
func (m *MockStore) ListAdminUsers(ctx context.Context, arg db.ListAdminUsersParams) ([]db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUsers", ctx, arg)
	ret0, _ := ret[0].([]db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUsers indicates an expected call of ListAdminUsers.
func (mr *MockStoreMockRecorder) ListAdminUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUsers", reflect.TypeOf((*MockStore)(nil).ListAdminUsers), ctx, arg)
}

// ListOperationLogs mocks base method.
func (m *MockStore) ListOperationLogs(ctx context.Context, arg db.ListOperationLogsParams) ([]db.OperationLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationLogs", ctx, arg)
	ret0, _ := ret[0].([]db.OperationLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOperationLogs indicates an expected call of ListOperationLogs.
func (mr *MockStoreMockRecorder) ListOperationLogs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationLogs", reflect.TypeOf((*MockStore)(nil).ListOperationLogs), ctx, arg)
}

// ListPermissionCodesByAdminUserID mocks base method.
func (m *MockStore) ListPermissionCodesByAdminUserID(ctx context.Context, adminUserID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionCodesByAdminUserID", ctx, adminUserID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionCodesByAdminUserID indicates an expected call of ListPermissionCodesByAdminUserID.
func (mr *MockStoreMockRecorder) ListPermissionCodesByAdminUserID(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionCodesByAdminUserID", reflect.TypeOf((*MockStore)(nil).ListPermissionCodesByAdminUserID), ctx, adminUserID)
}

// ListRolePermissions mocks base method.
func (m *MockStore) ListRolePermissions(ctx context.Context) ([]db.ListRolePermissionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissions", ctx)
	ret0, _ := ret[0].([]db.ListRolePermissionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissions indicates an expected call of ListRolePermissions.
func (mr *MockStoreMockRecorder) ListRolePermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissions", reflect.TypeOf((*MockStore)(nil).ListRolePermissions), ctx)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(ctx context.Context) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), ctx)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, arg)
}

// ListWallets mocks base method.
func (m *MockStore) ListWallets(ctx context.Context, arg db.ListWalletsParams) ([]db.ListWalletsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWallets", ctx, arg)
	ret0, _ := ret[0].([]db.ListWalletsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWallets indicates an expected call of ListWallets.
func (mr *MockStoreMockRecorder) ListWallets(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWallets", reflect.TypeOf((*MockStore)(nil).ListWallets), ctx, arg)
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx)
}

// UpdateAdminUserPassword mocks base method.
func (m *MockStore) UpdateAdminUserPassword(ctx context.Context, arg db.UpdateAdminUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminUserPassword indicates an expected call of UpdateAdminUserPassword.
func (mr *MockStoreMockRecorder) UpdateAdminUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminUserPassword", reflect.TypeOf((*MockStore)(nil).UpdateAdminUserPassword), ctx, arg)
}

// UpdateAdminUserRolesTx mocks base method.
func (m *MockStore) UpdateAdminUserRolesTx(ctx context.Context, arg db.UpdateAdminUserRolesTxParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminUserRolesTx", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminUserRolesTx indicates an expected call of UpdateAdminUserRolesTx.
func (mr *MockStoreMockRecorder) UpdateAdminUserRolesTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminUserRolesTx", reflect.TypeOf((*MockStore)(nil).UpdateAdminUserRolesTx), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockStore) UpdateUserPassword(ctx context.Context, arg db.UpdateUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockStoreMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockStore)(nil).UpdateUserPassword), ctx, arg)
}
